Repository Amarjha01/InfantCareCompass, pull requests merged in 2025-07, with the labels that each got.

#17 fix: update footer email to help@infantcarecompass.live
  client/src/components/Footer.jsx
Labels: GSSoC'25, level1

#19 Updated SignIn.jsx for https://github.com/Amarjha01/InfantCareCompass/issues/6
  client/src/pages/News.jsx
  client/src/pages/Registration.jsx
  client/src/pages/SignIn.jsx
Labels: bug, enhancement, GSSoC'25, level2

#47 Add Framer Motion animation to Navbar for better mobile UX
  client/package-lock.json
  client/package.json
  client/src/components/Header.jsx
Labels: enhancement, good first issue, GSSoC'25, level1

#64 Added a custom not found page
  client/src/App.jsx
  client/src/pages/NotFoundPage.jsx
  client/src/routes/routes.jsx
Labels: enhancement, GSSoC'25, level3

#69 Vaccine Reminder Feature
  client/package-lock.json
  client/package.json
  client/src/pages/VaccineReminder.jsx
  client/src/routes/routes.jsx
Labels: enhancement, GSSoC'25, level3

#72 Add License and Update README
  LICENSE
  README.md
Labels: documentation, good first issue, GSSoC'25, level1

#80 Made the navbar fully responsive
  client/src/components/Header.jsx
Labels: enhancement, GSSoC'25, level2

#95 [Feat]:added asyncHandler utility
  server/utils/asyncHandler.js
Labels: enhancement, GSSoC'25, level1

#139 I have added the contributor page
  client/src/components/Header.jsx
  client/src/pages/Contributors.jsx
  client/src/routes/routes.jsx
Labels: GSSoC'25, level3
